framework: mocha
blocklist:
  - "./test/target.spec.ts##Targets##should stringify and toString"
preRun:
  command:
    - echo ${REGION}
    - npm install         
postMerge:
  pattern: 
    - "./test/*.spec.ts"
preMerge:
  pattern:
    - "./test/*.spec.ts"
postRun:
  command:
    - node --version
    - echo ${REGION}
version: 1.0
